services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
  db:
    image: postgres:16
    networks:
      - app-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks:
  app-network:
    driver: bridge